language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 2.2.103
solution: Midnite81.HelperExtensions.sln
script:
  - dotnet restore
  - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
global:
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
  - DOTNET_CLI_TELEMETRY_OPTOUT=1
